# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='pic1',
            field=models.CharField(default='', max_length=500, verbose_name='商品图片 1'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='pic2',
            field=models.CharField(default='', max_length=500, verbose_name='商品图片 2'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='pic3',
            field=models.CharField(default='', max_length=500, verbose_name='商品图片 3'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='subtitle',
            field=models.CharField(default='', max_length=300, verbose_name='商品副标题'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='商品标题'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='商品链接'),
        ),
    ]
