# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20170514_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodityinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='commodityinfo',
            name='commodity_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, unique=True, verbose_name='商品 ID'),
        ),
    ]
