# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20170514_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='commodity_info',
        ),
    ]
